apiVersion: v1
kind: ConfigMap
metadata:
  name: common-panel-service
  namespace: funnelbuiler-solution
data:
  config.js: |
    module.exports = {
      BASE_URL: "https://auth-dev.nextivecloud.com/api/",
      SELLER_PANEL_URL: "https://sellerpanel-dev.nextivecloud.com"
    };
