### STAGE 1: Build ###
FROM node:20-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/
RUN yarn install --silent
COPY .env.example /app/.env
COPY . /app
RUN yarn build

## STAGE 2: NGINX ###
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/.env /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["node", ".output/server/index.mjs"]