apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-panel-service-webserver
  namespace: funnelbuiler-solution
spec:
  ingressClassName: nginx
  rules:
    - host: "*.bdfunnelbuilder.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: common-panel-service-webserver
                port:
                  number: 80
    - host: abc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: domain-service-webserver
                port:
                  number: 80
    - host: xyz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: domain-service-webserver
                port:
                  number: 80
    - host: xyz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: domain-service-webserver
                port:
                  number: 80
    - host: 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: domain-service-webserver
                port:
                  number: 80
