apiVersion: v1
kind: Service
metadata:
  name: common-panel-service-webserver
  namespace: funnelbuiler-solution
spec:
  selector:
    tier: common-panel-frontend
    layer: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80