name: Deploy to server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image and publish
        run: make docker
      - name: Set up kubectl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          # k8s-args: doctl k8s cluster kubeconfig show funnelbuilder
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl k8s cluster kubeconfig save --expiry-seconds 600 funnelbuilder
      - name: Deploy config to Kubernetes
        run: kubectl apply -f docker/common-panel-service/common
      - name: Deploy to Kubernetes
        run: kubectl apply -f docker/common-panel-service/nuxt-with-nginx